# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-poc',
                'doc_host': 'https://UpstatePedro.github.io',
                'git_url': 'https://github.com/UpstatePedro/nbdev-poc',
                'lib_path': 'nbdev_poc'},
  'syms': {'nbdev_poc.core': {'nbdev_poc.core.foo': ('core.html#foo', 'nbdev_poc/core.py')}}}
